### ISSUE TITLE
command warp puts in error in console

### ISSUE THREAD

**Issue by kreezxil** [61352151511/Random-Utilities#4]
```
[16:16:32] [Server thread/WARN]: Couldn't process command: 'warp'
java.lang.StringIndexOutOfBoundsException: String index out of range: -31
        at java.lang.String.substring(String.java:1931) ~[?:1.8.0_91]
        at com.sixonethree.randomutilities.utility.homewarp.WarpPoint.getWarps(WarpPoint.java:84) ~[WarpPoint.class:?]
        at com.sixonethree.randomutilities.common.command.warp.CommandWarp.executeCommandPlayer(CommandWarp.java:40) ~[CommandWarp.class:?]
        at com.sixonethree.randomutilities.common.command.ModCommandBase.func_184881_a(ModCommandBase.java:121) ~[ModCommandBase.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:102) [j.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:81) [j.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:915) [mb.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:894) [mb.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [ij.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [ij.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [g.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:664) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:386) [la.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

On dedicated Forge 1.9 build 1906 server. 

The chat in game only says:

Please state which warp you would to teleport to.
An unknown error occurred while attempting to perform this command.

In the help system it says:
Usage: command.warp.usage

**Comment by 61352151511** [comment]
I'm surprised that it's even loading on this forge version, I'm aware that there's quite a few changes in forge. I'll work on bug fixes now and will have a new release out by tomorrow.
